backend:
  name: github
  repo: JFish-ByHu/cms_repo
  branch: main

media_folder: "docs/public/uploads"
public_folder: "../uploads"

collections:
  - name: "zh_quick_start"
    label: "快速入门"
    folder: "docs/zh/quickStart"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "description", label: "描述", widget: "text", required: false }
      - { name: "body", label: "内容", widget: "markdown" }
